version: '3.7'

services:
  zf:
    build: .
    container_name: zf
    ports:
     - 80:80
    volumes:
     - .:/var/www
    depends_on:
     - mysql

  mysql:
    container_name: mysql
    image: mysql:8
    restart: on-failure
    environment:
      MYSQL_DATABASE: todo_list
      MYSQL_USER: zf
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
    volumes:
      - ./../dump/mysql:/var/lib/mysql
